#!/usr/bin/env bash
# Regenerate .claude/memory/INDEX.md from the frontmatter of research/ and
# lessons/ entries. Hand-editing the index loses entries whenever two sessions
# write it at once; generating it removes that failure mode entirely.
# Run: plugins/dev-workflow/scripts/memory-index.sh
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
. "$SCRIPT_DIR/lib/state.sh"

dir="${CLAUDE_PROJECT_DIR:-$PWD}"
mem="$dir/.claude/memory"
[ -d "$mem" ] || exit 0

# Read one flat frontmatter key from a file; empty if absent.
fm() { # <file> <key>
  sed -n '2,/^---$/p' "$1" 2>/dev/null \
    | grep -m1 "^$2:" \
    | sed -E "s/^$2:[[:space:]]*//; s/^\"(.*)\"$/\1/"
}

first_heading() { grep -m1 '^# ' "$1" 2>/dev/null | sed 's/^# //'; }
first_prose()   { grep -m1 -v -e '^$' -e '^#' -e '^---' "$1" 2>/dev/null | cut -c1-120; }

{
  echo "# Project Memory Index"
  echo "Generated by plugins/dev-workflow/scripts/memory-index.sh — do not edit by hand."
  echo ""
  echo "## Research"
  echo "One line per entry: - [topic](research/<file>.md) — one-line answer (YYYY-MM-DD)"
  echo ""
  for f in "$mem"/research/*.md; do
    [ -f "$f" ] || continue
    base=$(basename "$f")
    topic=$(fm "$f" topic);  [ -n "$topic" ]  || topic=$(first_heading "$f");  [ -n "$topic" ]  || topic="$base"
    answer=$(fm "$f" answer); [ -n "$answer" ] || answer=$(first_prose "$f")
    date=$(fm "$f" date)
    if [ -n "$date" ]; then
      echo "- [$topic](research/$base) — $answer ($date)"
    else
      echo "- [$topic](research/$base) — $answer"
    fi
  done | LC_ALL=C sort

  echo ""
  echo "## Lessons"
  echo "Mistakes already paid for. Level 2 is injected on a matching action; level 3 blocks it."
  echo ""
  for f in "$mem"/lessons/*.md; do
    [ -f "$f" ] || continue
    base=$(basename "$f")
    rule=$(fm "$f" rule); [ -n "$rule" ] || rule=$(first_heading "$f"); [ -n "$rule" ] || continue
    level=$(fm "$f" level); [ -n "$level" ] || level=1
    hits=$(fm "$f" hits);   [ -n "$hits" ]  || hits=0
    echo "- [L$level, ${hits} hit(s)] [$rule](lessons/$base)"
  done | LC_ALL=C sort
} | dw_atomic_write "$mem/INDEX.md"

exit 0
