#!/usr/bin/env bash
# Regenerate .claude/memory/INDEX.md from the frontmatter of research/ and
# lessons/ entries. Hand-editing the index loses entries whenever two sessions
# write it at once; generating it removes that failure mode entirely.
# Run: plugins/dev-workflow/scripts/memory-index.sh
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
. "$SCRIPT_DIR/lib/state.sh"

dir="${CLAUDE_PROJECT_DIR:-$PWD}"
mem="$dir/.claude/memory"
[ -d "$mem" ] || exit 0

# Read one flat frontmatter key from a file; empty if absent.
fm() { # <file> <key>
  sed -n '2,/^---$/p' "$1" 2>/dev/null \
    | grep -m1 "^$2:" \
    | sed -E "s/^$2:[[:space:]]*//; s/^\"(.*)\"$/\1/"
}

# Hit counters left the lesson frontmatter: .claude/memory/ is committed, so
# mutable counters there kept the tree dirty. They now live in
# .claude/state/lesson-stats.json, one line per slug, which is what lets a
# single awk pass collect them all.
TAB=$(printf '\t')
stats_lines=""
stats_file=$(dw_lesson_stats_file "$dir")
if [ -f "$stats_file" ]; then
  stats_lines=$(awk -v TAB="$TAB" '
    match($0, /"[^"]*"[[:space:]]*:[[:space:]]*\{/) {
      slug = substr($0, RSTART + 1); sub(/".*/, "", slug)
      n = 0
      if (match($0, /"hits"[[:space:]]*:[[:space:]]*[0-9]+/)) {
        v = substr($0, RSTART, RLENGTH); sub(/.*[^0-9]/, "", v); n = v + 0
      }
      print slug TAB n
    }' "$stats_file" 2>/dev/null)
fi

# Absent stats are the normal state of a fresh or freshly cloned project.
lesson_hits() { # <slug>
  lh__want=$1
  while IFS="$TAB" read -r lh__slug lh__n; do
    if [ "$lh__slug" = "$lh__want" ]; then
      printf '%s' "$lh__n"
      return 0
    fi
  done <<EOF
$stats_lines
EOF
  printf '0'
}

DW_INDEX_GUARD="do not edit by hand"

# This script owns INDEX.md, but it may land on a project where someone wrote
# one by hand. Never destroy that silently.
backup_handwritten_index() { # <index-file>
  [ -f "$1" ] || return 0
  grep -qF "$DW_INDEX_GUARD" "$1" 2>/dev/null && return 0
  cp "$1" "$1.bak" 2>/dev/null || return 0
  echo "dev-workflow: $1 was not generated by this script; the previous version was saved as $1.bak before regeneration." >&2
}

first_heading() { grep -m1 '^# ' "$1" 2>/dev/null | sed 's/^# //'; }
first_prose()   { grep -m1 -v -e '^$' -e '^#' -e '^---' "$1" 2>/dev/null | cut -c1-120; }

backup_handwritten_index "$mem/INDEX.md"

{
  echo "# Project Memory Index"
  echo "Generated by plugins/dev-workflow/scripts/memory-index.sh — $DW_INDEX_GUARD."
  echo ""
  echo "## Research"
  echo "One line per entry: - [topic](research/<file>.md) — one-line answer (YYYY-MM-DD)"
  echo ""
  for f in "$mem"/research/*.md; do
    [ -f "$f" ] || continue
    base=$(basename "$f")
    topic=$(fm "$f" topic);  [ -n "$topic" ]  || topic=$(first_heading "$f");  [ -n "$topic" ]  || topic="$base"
    answer=$(fm "$f" answer); [ -n "$answer" ] || answer=$(first_prose "$f")
    date=$(fm "$f" date)
    if [ -n "$date" ]; then
      echo "- [$topic](research/$base) — $answer ($date)"
    else
      echo "- [$topic](research/$base) — $answer"
    fi
  done | LC_ALL=C sort

  echo ""
  echo "## Lessons"
  echo "Mistakes already paid for. Level 2 is injected on a matching action; level 3 blocks it."
  echo ""
  for f in "$mem"/lessons/*.md; do
    [ -f "$f" ] || continue
    base=$(basename "$f")
    rule=$(fm "$f" rule); [ -n "$rule" ] || rule=$(first_heading "$f"); [ -n "$rule" ] || continue
    level=$(fm "$f" level); [ -n "$level" ] || level=1
    hits=$(lesson_hits "${base%.md}")
    echo "- [L$level, ${hits} hit(s)] [$rule](lessons/$base)"
  done | LC_ALL=C sort
} | dw_atomic_write "$mem/INDEX.md"

exit 0
